### ISSUE TITLE
Why is the background orange and not transparent, like in the documentation

### ISSUE THREAD

**Issue by guin0x** [wavespectra/wavespectra#88] opened 2023-07-08 10:40 UTC
Hi,

below image was generated with 
```
ds = ds.spec.split(fmax=f_max)
ds.spec.plot(kind='contourf')
```

I don't understand why the "background" is orange (which kinda relates to efth ~ 0.5), instead of transparent, as shown in the documentation.. (or if I plot with "contour")

![image](https://github.com/wavespectra/wavespectra/assets/35092729/d95e3dd9-d2e3-49ab-91cb-3408ef3ee2eb)

**Comment by rafa-guedes** [comment] 2023-07-10 22:12
I cannot reproduce it with one of the testing files in the library. It may have to do with the masking value used in the spec.plot method (efth_min) when applied to your data although in your case it seems to be masking intermediate values so I'm not sure.

**Comment by rafa-guedes** [comment] 2023-10-25 23:45
@guin0x do you still have this problem? If you want to send a reproducible example I could have a quick look. Otherwise I may close this issue since it hasn't got a response.

**Closed** 2023-10-26 07:35 UTC
Labels: question
